theme: jekyll-theme-hacker
permalink: none

title: strfry
description: "Random collection of stuff in encounter"
baseurl: ""


# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "images"
    values:
      image: true
