theme: jekyll-theme-hacker
permalink: none

title: strfry's blag
# description: "Random excerpts of stuff i do"
baseurl: 


# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "images"
    values:
      image: true

collections:
  projects:
    output: true
